image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - deploy

javascript_tests:
  stage: test
  script:
    - npm ci
    - CI=true npm test

lint_css:
  stage: test
  script:
    - npm ci
    - npm run lintcss
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - reports/*.xml
    reports:
      junit: reports/cssreport.xml

audit_js:
  stage: test
  script:
    - npx auditjs --prod --report --suppressExitError
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - reports/*.xml
    reports:
      junit: reports/scan_node_modules.xml

pages:
  stage: deploy
  script:
    - CI=true npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
