image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - deploy

run_tests:
  stage: test
  script:
    - npm ci
    - CI=true npm test

lint_css:
  stage: test
  script:
    - npm ci
    - npm run lintcss

pages:
  stage: deploy
  script:
    - CI=true npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
